android/src/main/AndroidManifest.xml
example/android/app/src/debug/AndroidManifest.xml
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/res/drawable/rn_edit_text_material.xml
example/ios/Podfile.lock
example/ios/ReactNativeIdnowVideoidentExample/LaunchScreen.storyboard
package.json
yarn.lock

Prettier for XML

---

README.md
android/build.gradle
example/android/build.gradle

-   [X] Code-documentation is created / adapted

JCenter note

---

.github/workflows/deploy_website.yml

Fix: Building the website

---

README.md

ProGuard note

---

README.md
package.json

chore: reworked package.json fields

---

website/docusaurus.config.js

Google analytics 

---

example/src/createFullSettings.ts

fix: example

---

android/build.gradle
android/proguard-rules.pro
website/docs/getting-started.mdx

feat: `consumerProguardFiles`

---

example/android/build.gradle
website/docs/getting-started.mdx

chore: Gradle

---

android/build.gradle

chore: fix Gradle file

---

android/build.gradle

feat: android update

---

example/ios/Podfile.lock
tokenstreet-react-native-idnow-videoident.podspec

feat: IDnow iOS SDK update

---

example/ios/Podfile.lock
tokenstreet-react-native-idnow-videoident.podspec

feat: IDnow SDK 5.3.0

---

src/expo/withIdnowVideoIdentSdk.ts

fix: Types

---

.github/workflows/main.yml

fix: Website deployment

---

website/docs/getting-started.mdx

docs: use_frameworks! note

---

examples/bare/ios/Podfile
src/expo/withIosIdnowVideoIdentSdk.ts
website/docs/getting-started.mdx

fix: Naming

---

examples/bare/ios/Podfile.lock

fix: lock files

---

examples/bare/ios/Podfile.lock
src/expo/util/__tests__/appendToFoundRegex.unit.spec.ts

chore: Podfile

---

examples/expo/package.json
examples/expo/yarn.lock
src/expo/withIosIdnowVideoIdentSdk.ts

fix: Expo dep

---

android/build.gradle
examples/bare/ios/Podfile.lock
tokenstreet-react-native-idnow-videoident.podspec

feat: IDnow 6

---

android/build.gradle
examples/bare/ios/Podfile.lock
tokenstreet-react-native-idnow-videoident.podspec

feat: IDnow update

---

android/build.gradle
examples/bare/ios/Podfile.lock
examples/expo/app.json
examples/expo/package.json
examples/expo/yarn.lock
src/expo/withAndroidIdnowVideoIdentSdk.ts

fix: Duplicate classes

---

examples/expo/app.json
src/expo/model/IConfigPluginProps.ts
src/expo/withAndroidIdnowVideoIdentSdk.ts
src/expo/withIdnowVideoIdentSdk.ts
src/expo/withIosIdnowVideoIdentSdk.ts
website/docs/getting-started.mdx

feat: Expo plugin config options

---

android/build.gradle
android/src/main/java/com/tokenstreetreactnativeidnowvideoident/ReactNativeIdnowSDK.java
android/src/main/java/com/tokenstreetreactnativeidnowvideoident/ReactNativeIdnowVideoidentModule.java
examples/bare/ios/Podfile.lock
tokenstreet-react-native-idnow-videoident.podspec

feat: Upgrade versions

---

examples/expo/app.json
website/docs/getting-started.mdx

docs: `InfoPlist`

---

examples/expo/package.json

chore: xcode command

---

examples/bare/yarn.lock
examples/expo/yarn.lock
yarn.lock

-   Add
-   Things
-   That
-   Happened

chore: Regenerated `yarn.lock` files

---

examples/bare/android/app/src/main/java/com/example/tokenstreetreactnativeidnowvideoident/MainActivity.kt
examples/bare/android/app/src/main/java/com/example/tokenstreetreactnativeidnowvideoident/MainApplication.kt

-   Add
-   Things
-   That
-   Happened

fix: Android example
